server:
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: 100MB  # 单个文件的大小
      max-request-size: 100MB  # 上传文件的总大小
  datasource:
    url: jdbc:mysql://8.129.121.95:3306/demo?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: lingsheng123.
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static
  freemarker:

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.*.pojo


#showSql
logging:
  level:
    com.demo: debug
    spring: info

##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800

#支付宝支付接口
alipay:
  #  url: https://openapi.alipay.com/gateway.do #支付宝网关（固定）
  #  appid: 2021002112601918     #商户appid
  #  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk6ra1Ex8TKi2rxPEc9lN9Hh8MZ6/4ctsLBq0JNJhXo583AJV9tAUvkO2quMqf24gchxtqtofwrhznzRrgskb4+xUThMUfmyv7DCwvUB93sGnDo76ppxzqDP2VZBcMNh3dR/EcrVs3RIH82eKHp4JncYYSUQZLTvOQS8QO/ystRa8z24MHMRcnkLJQD3FsYf9SewICFyPfAcFgUVi0JhHvDXryUOUnrA9OZR+/AimOPacbs2Z5Ng/Yg+tH3TavCCxTpzOUts8BdBYEmaa2DxsCu06+KLLIRItLZZpBzqeYb6GSZxx3/beKUeWb4mTO3DASkwQPRDlCrijhcD4+kLE5wIDAQAB
  #  app_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCv46jSXrEMTUDFBOzuqvNG+GGU2+rcTrpWpvGjcgH7+55Iet3X/v5pViuG2Ghl+gxkB13rohtNvyrxYRmbXAkli6TK2eEN4MtXYbBsB5eMPE28RrEqqJKtrlwQUwGdWePePtfl7Ozg/j//0m7BK2CS3rEsPKVibH0w4KFU34XR0qNk+ybuHgs4MTpOWku2s1vscWQmlgRUoPy+zZubF4mj1mT8AVaq7gEdnFVNq7QEkxeNGIPdbZgP8KzFmBOpmMCLLkVfDJ4jGuBemV8W8Y6XKgy7ntZQOyq4gio6CjGt28ou0rtQBPlGLRWRF7Rn+rMTDe+K//e1ocOVhNVguFm1AgMBAAECggEAWYmZHU5a7po9CI6TVoPryAsVEcRJ8NCbBxWBGOUmoXHbh6YUXKpQNKtLCSANNSxvNlSRuSwSnidc4ve9I1tcxKIrx5/Wc0wl91uhhbzvptHj+J47/i1GTefeseivf7yMxUxUd5V+mKKVTdN/0hIU3W9D3fMZddsod8NCHYSUCNVLYQC4nOm6Ke5ZEkfN/ovNyuwZqXnY0V8jZ2rCEaPAWRacpCeEq1UK6gozW8zVZvlVdH4nQsmXnEz4Dj1Vu+iR08KpyP8EkwnhHOsj3JEdkkY92AAtUHJkCUBD7QwuAp42Xd1cCNLs1lfJb6IhlcsfhM8zXpjh3fjQ0iwAeuZ02QKBgQDdO+Hx/gawFCcHbACZemBybEn6o9jsnRO64dDN6a+JeDekhOHHgqLTJ6JP+/63eShb7gjIqsVtLF8zdkdXogAiN7sk3f/YbtaAU0+KOvIBYN8WhStAfw67PA49oSc4P2iyHx+SSlvbNXFsn/XP4hYsCx6tb/hw0/Kpc9ZVEPfb1wKBgQDLh5aEMQlKQw1Cq9TxvO5+0cThllsKKAtPWUuc/pofmB1Zg1p8Dzgd7jPeE8fVjMMFDp7PtZbacRt8I8QM8Z4B2PKhtiDZZMhTaFWI/K3vro1CUM1DCBofgFk+EDUKecIrIwYIo5JkNLN/Q7OV+onNbWMEjRW8BWAbIwqL3FolUwKBgQCp/ZpWbD9NSp7WqBkp1QuIwEZz7TQAU43Wei8MGXSE57exlV07BNkB8KFaXiHRbqohQRzEu9spUP/xtf+JiXQa1sHYyTAOaNQvFFS4vSQ5BOtGDZs3WqnCGppCprJRGP/kZd/Hc5VzMXRu59ZkHq+0tfKjh7bZUzJRHC3jfT9GTwKBgESS9WqqnuevectJ2+Bq+Kwv/zbGkvv0DAN7IZfOzJzygokDUbxU4GJtPHqJjZ3s5FRS3b08AIyu6UTFRCvcSJF0yCMmGyFD7J71m0QhZnVICX4bfV0lYK/WbbsUeNqDtaEVFtZYTl2GyCeL5vkURdO6FE+XPYhxAzWBc+81mgXTAoGAQPZv7Ig5TNTeXUms2Y/FAcXuDt1f68jIzJMTR7YvshlXS3cBU0tzdil0BfIrZSeBOKHU3HMhooVuXr9oFdoq3ETa6nwF9sGCBcpzqMvtpqYbh1yl+VTzgOSXeN8Y08JTgiSFwsbkloQqSXtA4YoGdarPT+6HJ2bORNrmeZwSSSg=
  format: json  #固定jsons
  charset: UTF-8 #编码集，支持 GBK/UTF-8
  sign_type: RSA2
  notifyurl: https://www.lssell.cn/tt3/diancan/Ali/notifyUrl #回调接口
  urlparam: pages/home/home
  #沙箱测试
  url: https://openapi.alipaydev.com/gateway.do #支付宝网关（固定）
  appid: 2016110300789817     #商户appid
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl/VtYi4YDIioaRxRT8ljZP3NOW8Zcbjypg/JWpGxPU4QLXBstyv00VdFlw1Bu+4PMJuG6K08GXjBuX6DuVIL0hpvudtRL3fN2tQiczV5dRMpn1WNVHtyPdsCyWS5IyhzXBkvkdQhfj3kYEuQhdM4O9iI94t4F5kq51uBZLFSBEzNC1rUOg0RMy68iDfSiWOeDtaeCvumyk41xZdlSOfbpIeHSzMgAVSG6YRBMYaSa0kcTJz20SAXDdkE0OGKz/aH4KZW8uh3c3ByeIvkZTPm8FUPSuYMBdcadlyo2yrGd+aXJeLeDINMQtn8Bqm8pM2BQUFxXVravxs/1lC91tJeeQIDAQAB
  app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYK7iQFGzt2VonMiS0OXo0q43wspZMTO2f1Uek9GaVkm9wRmPTDPqCcTBAqsgdQQ2kmjfUWFWda6iPh55t+18be7f3eGdjLQyAIeATUpwj8pU5nZNDbKNfyTlHhRPPjad9I6Ouz6B+ThgSjUSKupMTK5ll1Q4F7oIX6cs4ItQ9MoNk8W3ArguYMju2tjw4gPq0JOoNrr79ZAB5DpNC2vlqL+ZWRjGe7Ze7U3aeArcwkCGWUq7MTd0YG5CI2w6fDhIISZ1QjO2xjtFuBrB8Qg99jbzxQd56zUllkGH5t8U9hWOeZH69KZ0gWG6nBlJTIFd/IESAPjMI7LJTJnn7qZJHAgMBAAECggEANYIiOx/Dkft89Q1v1KPlcgHlPn891IS0hiCUOc/rBqtgXkWSMpN8v0OX6RVkmszWREwqV5PcPyetNRNGRXw/3EUr0mxXRot/usqupXzGBOn3STQ8pVfdNwBmEN0dsz0naRyQIRdHY0KIunVMZc/nibUqEqHRdYqB2nDOkeXFZeL/OVFhcRnSvd8LDZeJEPM1AfwBOSa6NDLsgPI4CEeyetUEvhO3hph1SXg/X9jCkJCqMXOkQGswTdBvPt7l3/LoJwEmaoam0y6u0ujhwoYpQlCChRooZgOMDZCsQ+9VM6e6sJQMC4Qgdw9NBiQU5oCasbSzawKKR3Zy6tE7P7rB+QKBgQD8t2Q02NQ9Zrcv8aFgi7CgwoZwXykV5f8nJ+wKeKfKCOQFN7pabpVIFQ9wCavL8NQcryAM3lDM+KNJ8z55DQcm+zjIewiubFja8Y1MHI5Mim4XOJGQiqh0M4GHmNpbCG2It0hdFueGkF8nBO7Wz3y9p5aCO902yqiMzL+q6TkeDQKBgQCaJeKvJwXlyqOBNDetM7QrRif3JEOGxwVlJ5pAxxeuvx1tcYA8hNlZ4aLDLpI8Hd9hfiq3H9boXWdbQ/MznZf2nb36X7r0HzDxDwBPmJc5xjEF8C4jY8wS00rxH0tx7ZZVvUcGvOgp1XvF1Y6iSceDYG/2jECqukDgW/nPQA0wowKBgQCJTb6U8+XEgoUu+FJcmSja/zV54kn5St/pT0hwnANVwqTYrOGD9qcG5eJgVfDQOkWUXBXGyBcQdlqJeC5OKKTlKgM88ZPS6K0SL8E8RBuQPHn6BdMYvC0wDTfoC0U/xoF0kVgws5wRQWlhUs3NSigVBvPASHQ1K8CN10SfwF03FQKBgF+rF68hBvYA980efVePeUhKOE+YQBiLuHt5QrDlX3tivX7JLI9i3Ap+kSeV5chNue+mABi7OAPqxFTOLUhhjIjQibG0bDFKknNpngXIbEK9EHvg/qGUNHmSjTZs98PzcpQv7r7tyyD7j9/OlMGADMUquxJHJXNQOSeFrdrEo+sFAoGBAMixozRG4PNc79OL3OrC5h+thBRc7Mg75C8MefhlV1TL73WJ3DiiDsseddVKtNmouOQ/raQimTNf+gKBo1r842ofA/CYKaWop6bIPjn8DjekzMBvfYJdQbQtSH4wVuHkETBvC3DEYGXh0jO/MOkNeQy04XxAGs0tyoSMZB910/hi

#支付宝支付接口
boss:
  #  url: https://openapi.alipay.com/gateway.do #支付宝网关（固定）
  #  appid: 2021002112601918     #商户appid
  #  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk6ra1Ex8TKi2rxPEc9lN9Hh8MZ6/4ctsLBq0JNJhXo583AJV9tAUvkO2quMqf24gchxtqtofwrhznzRrgskb4+xUThMUfmyv7DCwvUB93sGnDo76ppxzqDP2VZBcMNh3dR/EcrVs3RIH82eKHp4JncYYSUQZLTvOQS8QO/ystRa8z24MHMRcnkLJQD3FsYf9SewICFyPfAcFgUVi0JhHvDXryUOUnrA9OZR+/AimOPacbs2Z5Ng/Yg+tH3TavCCxTpzOUts8BdBYEmaa2DxsCu06+KLLIRItLZZpBzqeYb6GSZxx3/beKUeWb4mTO3DASkwQPRDlCrijhcD4+kLE5wIDAQAB
  #  app_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCv46jSXrEMTUDFBOzuqvNG+GGU2+rcTrpWpvGjcgH7+55Iet3X/v5pViuG2Ghl+gxkB13rohtNvyrxYRmbXAkli6TK2eEN4MtXYbBsB5eMPE28RrEqqJKtrlwQUwGdWePePtfl7Ozg/j//0m7BK2CS3rEsPKVibH0w4KFU34XR0qNk+ybuHgs4MTpOWku2s1vscWQmlgRUoPy+zZubF4mj1mT8AVaq7gEdnFVNq7QEkxeNGIPdbZgP8KzFmBOpmMCLLkVfDJ4jGuBemV8W8Y6XKgy7ntZQOyq4gio6CjGt28ou0rtQBPlGLRWRF7Rn+rMTDe+K//e1ocOVhNVguFm1AgMBAAECggEAWYmZHU5a7po9CI6TVoPryAsVEcRJ8NCbBxWBGOUmoXHbh6YUXKpQNKtLCSANNSxvNlSRuSwSnidc4ve9I1tcxKIrx5/Wc0wl91uhhbzvptHj+J47/i1GTefeseivf7yMxUxUd5V+mKKVTdN/0hIU3W9D3fMZddsod8NCHYSUCNVLYQC4nOm6Ke5ZEkfN/ovNyuwZqXnY0V8jZ2rCEaPAWRacpCeEq1UK6gozW8zVZvlVdH4nQsmXnEz4Dj1Vu+iR08KpyP8EkwnhHOsj3JEdkkY92AAtUHJkCUBD7QwuAp42Xd1cCNLs1lfJb6IhlcsfhM8zXpjh3fjQ0iwAeuZ02QKBgQDdO+Hx/gawFCcHbACZemBybEn6o9jsnRO64dDN6a+JeDekhOHHgqLTJ6JP+/63eShb7gjIqsVtLF8zdkdXogAiN7sk3f/YbtaAU0+KOvIBYN8WhStAfw67PA49oSc4P2iyHx+SSlvbNXFsn/XP4hYsCx6tb/hw0/Kpc9ZVEPfb1wKBgQDLh5aEMQlKQw1Cq9TxvO5+0cThllsKKAtPWUuc/pofmB1Zg1p8Dzgd7jPeE8fVjMMFDp7PtZbacRt8I8QM8Z4B2PKhtiDZZMhTaFWI/K3vro1CUM1DCBofgFk+EDUKecIrIwYIo5JkNLN/Q7OV+onNbWMEjRW8BWAbIwqL3FolUwKBgQCp/ZpWbD9NSp7WqBkp1QuIwEZz7TQAU43Wei8MGXSE57exlV07BNkB8KFaXiHRbqohQRzEu9spUP/xtf+JiXQa1sHYyTAOaNQvFFS4vSQ5BOtGDZs3WqnCGppCprJRGP/kZd/Hc5VzMXRu59ZkHq+0tfKjh7bZUzJRHC3jfT9GTwKBgESS9WqqnuevectJ2+Bq+Kwv/zbGkvv0DAN7IZfOzJzygokDUbxU4GJtPHqJjZ3s5FRS3b08AIyu6UTFRCvcSJF0yCMmGyFD7J71m0QhZnVICX4bfV0lYK/WbbsUeNqDtaEVFtZYTl2GyCeL5vkURdO6FE+XPYhxAzWBc+81mgXTAoGAQPZv7Ig5TNTeXUms2Y/FAcXuDt1f68jIzJMTR7YvshlXS3cBU0tzdil0BfIrZSeBOKHU3HMhooVuXr9oFdoq3ETa6nwF9sGCBcpzqMvtpqYbh1yl+VTzgOSXeN8Y08JTgiSFwsbkloQqSXtA4YoGdarPT+6HJ2bORNrmeZwSSSg=
  format: json  #固定jsons
  charset: UTF-8 #编码集，支持 GBK/UTF-8
  sign_type: RSA2
  notifyurl: https://www.lssell.cn/tt3/diancan/notifyUrl #回调接口
  urlparam: pages/home/home
  WECHAT_APPID: wx66045ae0272bfb91
  WECHAT_MACH_ID: 1494713732
  WECHAT_key: D0D4AF14620A3450F2F0BFF237075543
  wxNOTIFYURL: https://www.lssell.cn/tt3/diancan/weChatPay
  UNIFIED_ORDER_URL: https://api.mch.weixin.qq.com/pay/unifiedorder #统一下单地址
  #沙箱测试
  url: https://openapi.alipaydev.com/gateway.do #支付宝网关（固定）
  appid: 2016110300789817     #商户appid
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl/VtYi4YDIioaRxRT8ljZP3NOW8Zcbjypg/JWpGxPU4QLXBstyv00VdFlw1Bu+4PMJuG6K08GXjBuX6DuVIL0hpvudtRL3fN2tQiczV5dRMpn1WNVHtyPdsCyWS5IyhzXBkvkdQhfj3kYEuQhdM4O9iI94t4F5kq51uBZLFSBEzNC1rUOg0RMy68iDfSiWOeDtaeCvumyk41xZdlSOfbpIeHSzMgAVSG6YRBMYaSa0kcTJz20SAXDdkE0OGKz/aH4KZW8uh3c3ByeIvkZTPm8FUPSuYMBdcadlyo2yrGd+aXJeLeDINMQtn8Bqm8pM2BQUFxXVravxs/1lC91tJeeQIDAQAB
  app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYK7iQFGzt2VonMiS0OXo0q43wspZMTO2f1Uek9GaVkm9wRmPTDPqCcTBAqsgdQQ2kmjfUWFWda6iPh55t+18be7f3eGdjLQyAIeATUpwj8pU5nZNDbKNfyTlHhRPPjad9I6Ouz6B+ThgSjUSKupMTK5ll1Q4F7oIX6cs4ItQ9MoNk8W3ArguYMju2tjw4gPq0JOoNrr79ZAB5DpNC2vlqL+ZWRjGe7Ze7U3aeArcwkCGWUq7MTd0YG5CI2w6fDhIISZ1QjO2xjtFuBrB8Qg99jbzxQd56zUllkGH5t8U9hWOeZH69KZ0gWG6nBlJTIFd/IESAPjMI7LJTJnn7qZJHAgMBAAECggEANYIiOx/Dkft89Q1v1KPlcgHlPn891IS0hiCUOc/rBqtgXkWSMpN8v0OX6RVkmszWREwqV5PcPyetNRNGRXw/3EUr0mxXRot/usqupXzGBOn3STQ8pVfdNwBmEN0dsz0naRyQIRdHY0KIunVMZc/nibUqEqHRdYqB2nDOkeXFZeL/OVFhcRnSvd8LDZeJEPM1AfwBOSa6NDLsgPI4CEeyetUEvhO3hph1SXg/X9jCkJCqMXOkQGswTdBvPt7l3/LoJwEmaoam0y6u0ujhwoYpQlCChRooZgOMDZCsQ+9VM6e6sJQMC4Qgdw9NBiQU5oCasbSzawKKR3Zy6tE7P7rB+QKBgQD8t2Q02NQ9Zrcv8aFgi7CgwoZwXykV5f8nJ+wKeKfKCOQFN7pabpVIFQ9wCavL8NQcryAM3lDM+KNJ8z55DQcm+zjIewiubFja8Y1MHI5Mim4XOJGQiqh0M4GHmNpbCG2It0hdFueGkF8nBO7Wz3y9p5aCO902yqiMzL+q6TkeDQKBgQCaJeKvJwXlyqOBNDetM7QrRif3JEOGxwVlJ5pAxxeuvx1tcYA8hNlZ4aLDLpI8Hd9hfiq3H9boXWdbQ/MznZf2nb36X7r0HzDxDwBPmJc5xjEF8C4jY8wS00rxH0tx7ZZVvUcGvOgp1XvF1Y6iSceDYG/2jECqukDgW/nPQA0wowKBgQCJTb6U8+XEgoUu+FJcmSja/zV54kn5St/pT0hwnANVwqTYrOGD9qcG5eJgVfDQOkWUXBXGyBcQdlqJeC5OKKTlKgM88ZPS6K0SL8E8RBuQPHn6BdMYvC0wDTfoC0U/xoF0kVgws5wRQWlhUs3NSigVBvPASHQ1K8CN10SfwF03FQKBgF+rF68hBvYA980efVePeUhKOE+YQBiLuHt5QrDlX3tivX7JLI9i3Ap+kSeV5chNue+mABi7OAPqxFTOLUhhjIjQibG0bDFKknNpngXIbEK9EHvg/qGUNHmSjTZs98PzcpQv7r7tyyD7j9/OlMGADMUquxJHJXNQOSeFrdrEo+sFAoGBAMixozRG4PNc79OL3OrC5h+thBRc7Mg75C8MefhlV1TL73WJ3DiiDsseddVKtNmouOQ/raQimTNf+gKBo1r842ofA/CYKaWop6bIPjn8DjekzMBvfYJdQbQtSH4wVuHkETBvC3DEYGXh0jO/MOkNeQy04XxAGs0tyoSMZB910/hi


#微信H5支付相关配置
wechatpay:
  WECHAT_APPID: wx66045ae0272bfb91
  appsecret: e1ac7aa5111e02079ade61c8bf9db9f5
  WECHAT_MACH_ID: 1494713732
  WECHAT_key: D0D4AF14620A3450F2F0BFF237075543
  #  NOTIFYURL: https://www.lssell.cn/tt1/diancan/notice/weChatPay
  NOTIFYURL: https://www.lssell.cn/tt3/diancan/order/weChatPay
  #  NOTIFYURL: https://www.gongjubaike.cn/gg2/diancan/notice/weChatPay
  UNIFIED_ORDER_URL: https://api.mch.weixin.qq.com/pay/unifiedorder #统一下单地址